name: Linter
on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  luacheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nebularg/actions-luacheck@v1
        with:
          files: 'lua'
