---
name: "Release"
on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  luarocks-release:
    runs-on: ubuntu-latest
    name: Luarocks Release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        if: env.LUAROCKS_API_KEY != null
      - name: Luarocks Upload
        uses: nvim-neorocks/luarocks-tag-release@v7
        if: env.LUAROCKS_API_KEY != null
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
        with:
          detailed_description: |
            A Neovim grammar checker powered by LLM.
          copy_directories: |
            {{ neovim.plugin.dirs }}
