name: Formatting

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - ".github/**"
      - "**.md"
  workflow_dispatch:

jobs:
  format-with-stylua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: v0.20.0
          args: --check .
