---
name: Run tests
on:
  pull_request: ~
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        neovim_version: ['stable']

    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        uses: nvim-neorocks/nvim-busted-action@v1
        env:
          GROQ_API_KEY_DANTE_NVIM: ${{ secrets.GROQ_API_KEY_DANTE_NVIM }}
        with:
          nvim_version: ${{ matrix.neovim_version }}
