name: Type Check Code Base
on:
  pull_request: ~
  push:
    branches:
      - main

jobs:
  build:
    name: Type Check Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Checkout dependency neodev
        uses: actions/checkout@v3
        with:
          repository: "folke/neodev.nvim"
          path: "deps/neodev.nvim"

      - name: Type Check Code Base
        uses: mrcjkb/lua-typecheck-action@v0
        with:
          checklevel: Warning
          configpath: .github/workflows/.luarc.json
          directories: |
            lua
            spec
