name: lua_ls-typecheck
on:
  pull_request: ~
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    name: Type Check Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Checkout dependency neodev
        uses: actions/checkout@v3
        with:
          repository: "folke/neodev.nvim"
          path: "deps/neodev.nvim"
      - name: Checkout neovim for type annotations
        uses: actions/checkout@v3
        with:
          repository: "neovim/neovim"
          path: "deps/neovim"

      - uses: leafo/gh-actions-lua@v9
        with:
          luaVersion: "5.1"
      - uses: leafo/gh-actions-luarocks@v4
      - name: install dependencies
        run: |
          luarocks init
          luarocks install --only-deps ./*.rockspec

      - name: Type Check Code Base
        uses: mrcjkb/lua-typecheck-action@v0.2.1
        with:
          configpath: .github/workflows/.luarc.json
          directories: |
            lua
